Authentication
Ayub-Khan/LBM pull request #4
Opened 2019-06-16 11:56 UTC by quratulain25

Login, Password Reset and Signup added.

2019-06-16 13:01 UTC, Ayub-Khan requested changes

2019-06-16 13:01 UTC, Ayub-Khan commented on LBM/settings.py
> +LOGOUT_REDIRECT_URL = '/'
Logout redirect to login page

2019-06-16 13:01 UTC, Ayub-Khan commented on LBM/settings.py
> +LOGIN_REDIRECT_URL = '/'
Remove pyc files.

2019-06-16 13:01 UTC, Ayub-Khan commented on LBM/settings.py
> +EMAIL_FILE_PATH = os.path.join(BASE_DIR, "sent_emails")
Why email backend ?

2019-06-16 13:01 UTC, Ayub-Khan commented on LBM/urls.py
> +    path('', TemplateView.as_view(template_name='home.html'), name='home'),
Shift view based url to management

2019-06-16 13:01 UTC, Ayub-Khan commented on management/urls.py
> +    path('signup/', views.SignUp.as_view(), name='signup')
No need for signup

2019-06-16 13:01 UTC, Ayub-Khan commented on management/views.py
> +from django.template import loader
Move to imports

2019-06-16 13:01 UTC, Ayub-Khan commented on management/views.py
> +# def index(request):
Remove comment

2019-06-16 13:01 UTC, Ayub-Khan commented on management/urls.py
> +    path('signup/', views.SignUp.as_view(), name='signup')
Remove all signup logic

2019-06-16 13:01 UTC, Ayub-Khan commented on management/views.py
> +    template_name = 'signup.html'
Remove signup

2019-06-17 15:47 UTC, quratulain25 commented on LBM/settings.py
> +LOGOUT_REDIRECT_URL = '/'
Shouldn't it redirect to home? As login option would be there?

2019-06-17 17:53 UTC, Ayub-Khan approved these changes
1 NIT

2019-06-17 17:53 UTC, Ayub-Khan commented on LBM/urls.py
>      path('management/', include('django.contrib.auth.urls')),
management ko accounts kar do

2019-06-17 17:53 UTC, Ayub-Khan commented on LBM/settings.py
> +LOGOUT_REDIRECT_URL = '/'
direct login is better

2019-06-19 14:42 UTC, merged